influxdb:
    image: tutum/influxdb:latest
    ports:
    - "8083:8083"
    - "8086:8086"
    expose:
    - "8090"
    - "8099"
    environment:
    - PRE_CREATE_DB=cadvisor

cadvisor:
    image: google/cadvisor:latest
    links:
    - influxdb
    command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxdb:8086
    restart: always
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    ports:
    - "8080:8080"

grafana:
    image: grafana/grafana:latest
    links:
    - influxdb
    ports:
    - "3000:3000"
    environment:
    - HTTP_USER=admin
    - HTTP_PASS=admin
    - INFLUXDB_HOST=influxdb
    - INFLUXDB_PORT=8086
    - INFLUXDB_NAME=cadvisor
    - INFLUXDB_USER=root
    - INFLUXDB_PASS=root
